### ISSUE TITLE
Very cool project but I don't understand part of the guide

### ISSUE THREAD

**Issue by snipecoder** [openiap/zone-mta-ai-spam-check#1]
Hello

That looks very good.

But why should I copy the config files when they are already there? Also, I am using the zone-mta-template. the guide is not that clear. also, what is the MX part? I am using ZoneMTA as a relay.

The current stage is good for production? I see some parts are commented on.

Also, I have noticed that I can set one zone:  sendingZone: 'default'. Can I put multiple zones that will work?

**Comment by skadefro** [comment]
this project has an dependency on "zone-mta" and starts it from within node_modules
but you don't want the default config, so you need to copy the config folder from zone-mta and set it up, to match what you need, and then app.js will copy that into node_modules

I ran this in `production` for my company a few months but then i lost the IP i had in google cloud, and after a few tries of grabbing IP's that all had a low confidence score (the IP you are sending from, needs to have a low score at [talos](https://www.talosintelligence.com/reputation_center/) to deliver email to most big providers like google/office 365 ) i kinda gave up and stopped using it. 

I do miss it, it is **extremely** efficient in removing spam, so you peaked my interest in trying to set it up again. Thou not sure if i want to retry in google cloud, or just give up and find a different provider.

I original developed it, to support multiple sendingZone, but right now it only supports one. ( i wanted to move that from the config/default.js to the database so you can setup sendingZone per domain ) but never got around to adding that.
So both this plugin and the web interface [zone-mta-web](https://github.com/openiap/zone-mta-web) is semi hardcoded to use "default" for delivering emails.

I made this, in hopes there was a need and i could make a little money either providing it as a service or sell it as a closed source solution. But with no interested besides my self using it, i decided to just "throw it out there" ...  So if you can use it, that would make me happy, then it was not a complete waste of time :-)

**Comment by snipecoder** [comment]
Very good. Would you like a payment for integrating this into my ZoneMTA setup with a few adjustments, such as multiple sending zones?

Also, where did you get the API key? It’s not cheap. I saw some options to use a free one like the one used in the Visual Studio ChatGPT plugin, but I’m not sure how to obtain it.

Actually, I have a lot of subnets from ARIN/RIPE that are cleaned. If you want, we can collaborate on something. Let me know. I need that AI spam filter service, so why don't others need it?

Good project, out of the box. It can definitely be monetized. **Looking forward to your reply**, it sounds like we can do something together. :)

P.S.: It would be awesome if that was built for Haraka. Haraka has many more filters than ZoneMTA and could work much better.

**Comment by snipecoder** [comment]
What is the difference between [zone-mta-web](https://github.com/openiap/zone-mta-web) and the regular zmta-admin?

**Comment by skadefro** [comment]
[zmta-webadmin](https://github.com/zone-eu/zmta-webadmin) communicates directly with MongoDB and Zone-MTA's API. And to retrieve events, you need to install an additional plugin. While you **can** use it to manage a quarantine zone, it is not ideal for sharing with non-admin users due to its limited access control.

Originally, I used zmta-webadmin and intended to customize it to suit my needs. However, I eventually rewrote the plugin to integrate with my OpenFlow platform instead. This approach allows me to avoid direct interactions with MongoDB and Zone-MTA's API. By leveraging OpenFlow's access control lists and enhanced security features, I could create a multitenant solution that easily accommodates limited user accounts and delegation of control. And i could the extend this to also log all events into a time series collection for both easy reporting using grafana and to show in the zmta-webadmin website.

With the new setup, you configure things using the [zone-mta-web](https://github.com/openiap/zone-mta-web) interface, and these configurations inherit permissions for archived emails, quarantine emails, and event handling. Currently, only an admin can perform create those, thou. Since configurations can be user-specific or domain-wide, this allows for the creation of very fine-grained setups.

Additionally, because the configuration is managed by OpenFlow, we can utilize watches (change streams) to instantly update the plugin's settings as changes occur in the database, if creating of domains and/or config of the plugin had been in the config/default.js file, you would need to restart the mail server for those to take effect. 

I must admit that the housekeeping jobs I created for re-applying permissions are not the most elegant solution. I believe this could be improved upon at a later stage. If you are not processing several hundred thousand emails per day, this might suffice temporarily.

I am fully booked for the next 1½ months and cannot take on larger projects at this time. However, I always have time for a small 'meet and greet', you can see my free time slots [here](https://calendly.com/openiap/30min)
